<?php

$finder = PhpCsFixer\Finder::create()
	->in(__DIR__);

$config = PhpCsFixer\Config::create()
	->setIndent("\t")
	->setLineEnding("\n")
	->setRules(
		[
			'@PHP70Migration'                               => true,
			'@PHP71Migration'                               => true,
			'@PSR2'                                         => true,
			'align_multiline_comment'                       => true,
			'array_indentation'                             => true,
			'array_syntax'                                  => ['syntax' => 'short'],
			'binary_operator_spaces'                        => ['operators' => ['=>' => 'align_single_space_minimal', '=' => 'single_space']],
			'unary_operator_spaces'                         => false,
			'blank_line_after_opening_tag'                  => true,
			'blank_line_before_statement'                   => ['statements' => ['declare', 'throw', 'try']],
			'braces'                                        => ['position_after_functions_and_oop_constructs' => 'same'],
			'combine_consecutive_issets'                    => true,
			'combine_consecutive_unsets'                    => true,
			'comment_to_phpdoc'                             => true,
			'compact_nullable_typehint'                     => true,
			'concat_space'                                  => ['spacing' => 'one'],
			'dir_constant'                                  => true,
			'elseif'                                        => false,
			'escape_implicit_backslashes'                   => true,
			'explicit_indirect_variable'                    => true,
			'explicit_string_variable'                      => true,
			'final_internal_class'                          => true,
			'fully_qualified_strict_types'                  => true,
			'function_to_constant'                          => ['functions' => ['get_class', 'get_called_class', 'php_sapi_name', 'phpversion', 'pi']],
			'heredoc_to_nowdoc'                             => true,
			'list_syntax'                                   => ['syntax' => 'long'],
			'logical_operators'                             => true,
			'method_argument_space'                         => ['on_multiline' => 'ensure_fully_multiline'],
			'method_chaining_indentation'                   => true,
			'multiline_comment_opening_closing'             => true,
			'no_alternative_syntax'                         => true,
			'no_binary_string'                              => true,
			'no_extra_blank_lines'                          => ['tokens' => ['break', 'continue', 'extra', 'return', 'throw', 'use', 'parenthesis_brace_block', 'square_brace_block', 'curly_brace_block']],
			'no_null_property_initialization'               => true,
			'no_short_echo_tag'                             => true,
			'no_spaces_around_offset'                       => true,
			'no_spaces_inside_parenthesis'                  => true,
			'no_superfluous_elseif'                         => true,
			'no_superfluous_phpdoc_tags'                    => true,
			'no_trailing_comma_in_list_call'                => true,
			'no_trailing_comma_in_singleline_array'         => true,
			'no_trailing_whitespace'                        => true,
			'no_unneeded_curly_braces'                      => true,
			'no_unneeded_final_method'                      => true,
			'no_unreachable_default_argument_value'         => true,
			'no_unset_on_property'                          => true,
			'no_useless_else'                               => true,
			'no_useless_return'                             => true,
			'no_whitespace_before_comma_in_array'           => true,
			'non_printable_character'                       => ['use_escape_sequences_in_strings' => true],
			'not_operator_with_successor_space'             => false,
			'normalize_index_brace'                         => true,
			'object_operator_without_whitespace'            => true,
			'ordered_class_elements'                        => true,
			'ordered_imports'                               => true,
			'php_unit_internal_class'                       => true,
			'php_unit_method_casing'                        => true,
			'php_unit_ordered_covers'                       => true,
			'php_unit_set_up_tear_down_visibility'          => true,
			'php_unit_strict'                               => true,
			'php_unit_test_annotation'                      => true,
			'php_unit_test_case_static_method_calls'        => ['call_type' => 'this'],
			'php_unit_test_class_requires_covers'           => true,
			'phpdoc_add_missing_param_annotation'           => true,
			'phpdoc_order'                                  => true,
			'phpdoc_trim_consecutive_blank_line_separation' => true,
			'phpdoc_types_order'                            => true,
			'return_assignment'                             => true,
			'semicolon_after_instruction'                   => true,
			'single_line_comment_style'                     => true,
			'single_quote'                                  => ['strings_containing_single_quote_chars' => true],
			'standardize_not_equals'                        => true,
			'strict_comparison'                             => false,
			'string_line_ending'                            => true,
			'trailing_comma_in_multiline_array'             => true,
			'trim_array_spaces'                             => true,
			'yoda_style'                                    => false,
		]
	)->setFinder($finder);

return $config;
